import { PGlite } from '@electric-sql/pglite';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const db = new PGlite();
await db.exec(`create role anon nologin; create role authenticated nologin; create role service_role nologin bypassrls;
create schema auth;
create table auth.users(id uuid primary key,email text,raw_app_meta_data jsonb default '{}');
create table auth.sessions(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id));
create table auth.refresh_tokens(id bigint generated always as identity,user_id text);
create function auth.uid() returns uuid language sql stable as $$ select (nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid $$;
create function auth.jwt() returns jsonb language sql stable as $$ select nullif(current_setting('request.jwt.claims',true),'')::jsonb $$;
grant usage on schema auth to authenticated,service_role;`);
await db.exec(await readFile(new URL('../migrations/202610070001_chatbot.sql',import.meta.url),'utf8'));
const a='00000000-0000-0000-0000-000000000001', b='00000000-0000-0000-0000-000000000002', c='00000000-0000-0000-0000-000000000003';
await db.query(`insert into auth.users(id,email,raw_app_meta_data) values($1,'admin@test.it','{"chatbot_role":"admin"}'),($2,'user@test.it','{}'),($3,'manager@test.it','{}')`,[a,b,c]);
await db.exec(await readFile(new URL('../migrations/202610070002_admin_usage.sql',import.meta.url),'utf8'));
async function asUser(id, claims={}) { await db.exec('reset role');await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:id,iat:Math.floor(Date.now()/1000),...claims})]);await db.exec('set role authenticated'); }
async function save(kind,target,payload) { return db.query('select public.chatbot_admin_save($1,$2,$3)',[kind,target,JSON.stringify(payload)]); }
const profile=(role,active=true) => ({display_name:'Test',role,active,monthly_requests:2,requests_per_minute:20,concurrent_requests:1});
await asUser(a);
const kb=(await db.query("insert into public.knowledge_bases(name) values('Shared') returning id")).rows[0].id;
await db.query("insert into public.documents(knowledge_id,filename,chunks_count) values($1,'test.pdf',1)",[kb]);
const conv=(await db.query("insert into public.conversations(title,knowledge_id) values('Private',$1) returning id",[kb])).rows[0].id;
await db.query("select public.save_chat_turn($1,'q','a','[]')",[conv]);
await asUser(b,{app_metadata:{chatbot_role:'admin'}});
assert.equal((await db.query('select public.chatbot_role() as role')).rows[0].role,'user');
await assert.rejects(save('profile',b,profile('admin')));
await assert.rejects(db.query("update public.app_profiles set role='admin' where id=$1",[b]));
assert.equal((await db.query('select * from public.conversations')).rows.length,0);
assert.equal((await db.query('select * from public.knowledge_bases')).rows.length,1);
await asUser(a);
await save('knowledge',kb,{shared:false,members:[]});
await asUser(b);
assert.equal((await db.query('select * from public.knowledge_bases')).rows.length,0);
assert.equal((await db.query('select * from public.documents')).rows.length,0);
assert.equal((await db.query('select public.chatbot_kb_access($1) as allowed',[kb])).rows[0].allowed,false);
await asUser(a);await save('profile',c,profile('manager'));await save('knowledge',kb,{shared:false,members:[{user_id:c,can_manage:true}]});
await asUser(c);
await db.query("insert into public.documents(knowledge_id,filename,chunks_count) values($1,'manager.pdf',1)",[kb]);
await assert.rejects(db.query("insert into public.knowledge_bases(name) values('Forbidden')"));
await asUser(a);await save('profile',c,profile('user'));await asUser(c);
await assert.rejects(db.query("insert into public.documents(knowledge_id,filename,chunks_count) values($1,'forbidden.pdf',1)",[kb]));
await asUser(a);
await assert.rejects(save('profile',a,profile('user')));
await assert.rejects(save('profile',a,profile('admin',false)));
await assert.rejects(save('force_password',a,{}));
const model={provider:'ollama',model_id:'test',name:'Test',enabled:true,shared:false,input_per_million:1,output_per_million:2,currency:'USD',members:[{user_id:b}]};
await save('model','ollama:test',model);
await asUser(b);assert.equal((await db.query("select * from public.app_models where key='ollama:test'")).rows.length,1);
await asUser(c);assert.equal((await db.query("select * from public.app_models where key='ollama:test'")).rows.length,0);
await asUser(a);await save('profile',b,profile('user'));await save('knowledge',kb,{shared:false,members:[{user_id:b}]});
await db.exec('reset role; set role service_role');
const req=(await db.query('select public.chatbot_reserve_request($1,$2,null) as id',[b,kb])).rows[0].id;
await assert.rejects(db.query('select public.chatbot_reserve_request($1,$2,null)',[b,kb]));
await db.query("update public.usage_events set status='success' where id=$1",[req]);
await db.query("insert into public.usage_events(user_id,operation,status,provider,model_id,input_tokens,output_tokens) values($1,'chat','success','ollama','test',10,20)",[b]);
const req2=(await db.query('select public.chatbot_reserve_request($1,$2,null) as id',[b,kb])).rows[0].id;
await db.query("update public.usage_events set status='error' where id=$1",[req2]);
await assert.rejects(db.query('select public.chatbot_reserve_request($1,$2,null)',[b,kb]));
await asUser(b);assert.equal((await db.query('select * from public.usage_events')).rows.length,3);
await assert.rejects(db.query("insert into public.usage_events(operation,status) values('chat','success')"));
await asUser(c);assert.equal((await db.query('select * from public.usage_events')).rows.length,0);
await asUser(a);await save('profile',b,profile('user',false));await asUser(b);
assert.equal((await db.query('select * from public.knowledge_bases')).rows.length,0);
assert.equal((await db.query('select * from public.app_models')).rows.length,0);
await asUser(a);await save('profile',b,profile('user'));await save('revoke_sessions',b,{});await asUser(b);
assert.equal((await db.query('select public.chatbot_role() as role')).rows[0].role,null);
await asUser(a);assert.ok((await db.query('select * from public.admin_audit')).rows.length>0);
await db.exec('reset role; set role anon');for(const table of ['app_profiles','usage_events','admin_audit','knowledge_members','app_models','model_members']) await assert.rejects(db.query(`select * from public.${table}`));
await db.close();console.log('Admin RLS passed: live roles, KB isolation, manager scope, model ACL, last admin, accounting permissions, quotas, suspension and session revocation.');
